name: quotez
description: "A Quotes app made with Flutter."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2

dependencies:
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.3
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  quotez_client:
    path: ../quotez_client
  riverpod_annotation: ^2.3.5
  screenshot: ^3.0.0
  serverpod_flutter: 2.0.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
