name: quotez_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  serverpod: 2.0.1
  serverpod_serialization: 2.0.1

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
  very_good_analysis: ^6.0.0
